# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true

    - name: Deploy
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SERVER_IP }} #你的nginx服务器公网ip
        port: ${{ secrets.SERVER_PORT }} #你的nginx服务器ssh端口
        username: ${{ secrets.SERVER_USERNAME }} #你的nginx服务器用户名
        password: ${{ secrets.SERVER_PASSWORD }} #你的nginx服务器密码
        localDir: "yudao-server/target/yudao-server.jar" #你vue项目build好的文件的路径,每次服务器上会自动删除对应的文件夹后重新覆盖
        remoteDir: ${{ secrets.SERVER_DESTINATION_ADMIN }} #你要把你build好的文件夹放到nginx服务器上的什么位置，一般都是nginx配置的站点路径
